### ISSUE TITLE
Plugin Breaks When Updating ACF To Version 5.7.11

### ISSUE THREAD

**Issue by jroy813** [MarieComet/mc-acf-flexible-template#15]
When upgrading the the newest ACF the ACF Templates turn into one large text field instead of the normal flexible content fields (Screenshot Below)
![2019-02-11_1644](https://user-images.githubusercontent.com/7685051/52595838-d93b1280-2e1c-11e9-9f2d-f378357f034d.png)
. This also breaks things on the front-end. I'm unsure of the exact cause, but here is the link to the ACF release: https://www.advancedcustomfields.com/blog/acf-5-7-11-release/ . 

Please help with this as soon as you can.

Love the plugin and would like to keep using it!

**Comment by MarieComet** [comment]
Can you explain "This also breaks things on the front-end."?

**Comment by jroy813** [comment]
I'm calling the ACF Flexible layout field as an array and looping through the array items to display the content based on the field_name and the value associated with it. I think some of the key-value pairs were changed with the update. Some of the items in the array have empty key's now. Here is a var_dump before and after:

**Before Update:**
`1 => 
    array (size=3)
      'acf_fc_layout' => string 'main_content_block' (length=18)
      'customize_section_content' => string 'Custom' (length=6)
      'content_block_group' => 
        array (size=3)
          'main_content' => 
            array (size=2)
              ...
          'sidebar_content' => 
            array (size=6)
              ...
          'template_part_version' => string '1' (length=1)
  2 => 
    array (size=3)
      'acf_fc_layout' => string 'callouts' (length=8)
      'customize_section_content' => string 'Custom' (length=6)
      'callout_group' => 
        array (size=2)
          'cta_tile' => string '' (length=0)
          'template_part_version' => string '1' (length=1)`

**After Update:**
`1 => 
    array (size=2)
      'acf_fc_layout' => string 'main_content_block' (length=18)
      '' => 
        array (size=1)
          '' => string '1' (length=1)
  2 => 
    array (size=2)
      'acf_fc_layout' => string 'callouts' (length=8)
      '' => 
        array (size=1)
          '' => string '1' (length=1)`

**Comment by MarieComet** [comment]
Thanks for details.
I'm not sure I'm undertanding from where your var_dump come from ? Are you displaying your ACF templates (from acf-flexible-template plugin) in front-end ?

**Comment by MarieComet** [comment]
After some searchs, it seems there is changes in `acf_maybe_get_field` function, which cause `get_field_object` return nothing.
I see there is other problems with the new fields API, related to this version on ACF support forum.
I'm waiting for some fixes from ACF. For now just going back to 5.7.10 version.

**Comment by MarieComet** [comment]
A fix has been published by ACF, please download 5.7.11 again and let me know if it's ok for you.

**Comment by jroy813** [comment]
I re-installed ACF 5.7.11 and it now works. Looks like they did fix whatever was wrong. Thank you very much for looking into it!

**Comment by lewebsimple** [comment]
ACF Pro 5.7.12 seems to have broken things again...

**Comment by MarieComet** [comment]
@lewebsimple Hi, tested with ACF Pro 5.8 and no issue on my side, can you confirm ?

**Comment by jroy813** [comment]
Hey Marie,

Everything seems to be working on my end :)

**Comment by MarieComet** [comment]
I'm closing this issue.
Please feel free to open a new issue if needed.
