### ISSUE TITLE
Is this plugin is dead?

### ISSUE THREAD

**Issue by BeholdPL** [MarieComet/mc-acf-flexible-template#16]
What about some updates?

**Comment by MarieComet** [comment]
> Is this plugin is dead?

No, this plugin is not dead.

> What about some updates?

About what would you like some updates ? Did you encounter an issue ? Or would you like other features ?

**Comment by BeholdPL** [comment]
Ok :) 

So my problem is that in 5.1 and newest I do not see plugin's buttons... Im using classic editor, I was trying with 5.2 too, with other (defaults) templates also. So I assumed that is not compatible with new versions.

**Comment by MarieComet** [comment]
Ok, so can you please open a new issue, select "bug report" and give more details as asked in the issue template ?

I'm closing this one.

Thanks.
