### ISSUE TITLE
Fails with ACF 5.10

### ISSUE THREAD

**Issue by drzraf** [MarieComet/mc-acf-flexible-template#23]
**Describe the bug**
Stopped working with ACF 5.10

**To Reproduce**
The "Save template" tooltip containing `Name the template : * ` does not show the `name` text input anymore.

**Screenshots**
![Screenshot from 2021-10-20 15-33-30](https://user-images.githubusercontent.com/1169926/138151264-a59cb20b-6680-4db3-a32f-633188fe58d7.png)

**WordPress and ACF Versions**
WordPress version :
ACF version: 5.10
ACF Pro version: 5.10

The reason is that `acf_render_field_label` now uses `acf_esc_html()` which strips the necessary markup.

**Comment by MarieComet** [comment]
Hey, thanks for the report.
Please download the last version of the repository and let me know if that's fixed for you.

**Comment by drzraf** [comment]
It works!
Thank you!
