### ISSUE TITLE
Respect WordPress coding standards

### ISSUE THREAD

**Issue by Mahjouba91** [MarieComet/mc-acf-flexible-template#3]
See https://make.wordpress.org/core/handbook/best-practices/coding-standards/php/

**Comment by MarieComet** [comment]
In progress
https://github.com/MarieComet/mc-acf-flexible-template/commit/1d7f77f0e2de2c70a1297fc62bd7fe01f88912ba

https://github.com/MarieComet/mc-acf-flexible-template/commit/21de0666c623ef5d64a9b4b560c049c0eb768b09

https://github.com/MarieComet/mc-acf-flexible-template/commit/efe0a9464d1c9d2e6fbfb8c063173a15df98dda7

https://github.com/MarieComet/mc-acf-flexible-template/commit/1bd07d767c8915b86de61e0da0e8b86b7c5cbf6f

**Comment by Mahjouba91** [comment]
Il te manque deux choses de ce que je vois sur les derniers commits pour l'instant : 

- peu importe si les accolades ne sont pas nécessaires pour les if (exemple d'une seule ligne de code), il faut les utiliser.
- Espaces après les négations de type "!"

Conseil : Utiliser l'IDE PHP Storm, avec une seule commande on peut appliquer tous les coding standards d'un coup : https://gist.github.com/Rarst/1370155

**Comment by MarieComet** [comment]
https://github.com/MarieComet/mc-acf-flexible-template/commit/2d3926b8cf9f804f5d2502cd1c63b3e901be9e8d

Merci @Mahjouba91 !
