### ISSUE TITLE
Template Names

### ISSUE THREAD

**Issue by NewJenk** [MarieComet/mc-acf-flexible-template#5]
Great work on the plugin!

I noticed that when saving templates, they can have the same name, e.g. if you save a template 'Test' you can then save another template 'Test'. Is it possible to give an alert to the user if saving a template that already has that name (or append a number to the template name)?

**Comment by MarieComet** [comment]
Hi @NewJenk, yes you're right on this point.
See my last commit https://github.com/MarieComet/mc-acf-flexible-template/commit/b8cd6647409def652b56dbeb4c53445daf063b6f
I've added a check on template name before save them, if an existing template has the same name, an error is shown.
What do you think ?

**Comment by NewJenk** [comment]
Hi @MarieComet,

Thanks for responding so quickly - the fix is great!
