### ISSUE TITLE
Some kind of problem with option page dedicated to archive CPT page

### ISSUE THREAD

**Issue by webaxones** [MarieComet/mc-acf-flexible-template#6]
Hi,
Got options page to customize my archive CPT pages and they seem not to be correctly treated by your plugin. Just look at the attached picture :)
![bug](https://user-images.githubusercontent.com/17084006/35434605-088361a8-0288-11e8-88aa-c2b535285b67.png)

Thanks ^^

**Comment by MarieComet** [comment]
Fixed in https://github.com/MarieComet/mc-acf-flexible-template/commit/c76de5fe1c846f2b33824371937217f7f14610f5
