### ISSUE TITLE
Your Plugin has a lot of potential, great work!!!

### ISSUE THREAD

**Issue by carfis** [MarieComet/mc-acf-flexible-template#7]
Hi Marie, 
Today, I discovered your plugin, and it is what I always needed since I use the flexible content a lot.

I found some cases when the "Load template" and "Save template" buttons are not displayed.

1. If the flexible content field is loaded with a clone field
![grafik](https://user-images.githubusercontent.com/11331154/35561388-6eb4e886-05b0-11e8-8cb0-750225ce90d4.png)

2. When the Field Group has more than one field type, for example, a text field and then a flexible content:
![grafik](https://user-images.githubusercontent.com/11331154/35561406-82ad8866-05b0-11e8-9f3e-71dda6e7f654.png)

for case 1
I looked at the class MC_Acf_Flexible_Template, and I added to the actions the type=clone

```
// add option settings in flexible field
add_action( 'acf/render_field_settings/type=flexible_content', array( $this, 'mc_ft_acf_field_groups_add_settings' ), 10, 1 );
```

```
// add option settings in flexible field clone
add_action( 'acf/render_field_settings/type=clone', array( $this, 'mc_ft_acf_field_groups_add_settings' ), 10, 1 );
```

![grafik](https://user-images.githubusercontent.com/11331154/35561455-a58c504c-05b0-11e8-86ca-0f3c1631f14f.png)

But I couldn't find how to display the save buttons.

Carlos

**Comment by MarieComet** [comment]
Hi Carlos,
thanks for you feedback, I will test your usecases in the next days and come back to you.

Marie.

**Comment by MarieComet** [comment]
Hi Carlos,

After some tests : 
1. Flexible field displayed in a clone field : I can't reproduce, when I display my flexible field in a clone field ("seamless" or "group" display), the buttons appears and import/export works.
So I thing it's an other problem (not clone field related).

2. Group field with flexible field and other field : I can't reproduce etiher : 
![image](https://user-images.githubusercontent.com/7976501/35768529-5765b8e0-08fd-11e8-9660-8a5969f212a8.png)

If you want to give me an export of your fields I will do some tests.

**Comment by carfis** [comment]
Hi Marie,
I tested the flexible content again. I think the problem was on my installation between the acf-json folder and database. I checked that on a multisite; maybe the field group was not loaded from the right place.

The fix was straightforward :(  I saved the flexible content with "Save and load templates functionality" disabled and then I enabled it again.

![grafik](https://user-images.githubusercontent.com/11331154/35768818-28c3a902-0902-11e8-808b-927514336170.png)

Then
![grafik](https://user-images.githubusercontent.com/11331154/35768873-d5a2971e-0902-11e8-996a-bdc76477547d.png)

![grafik](https://user-images.githubusercontent.com/11331154/35768901-0c38e102-0903-11e8-9dd2-fe703dd03d93.png)

Thank you very much!

**Comment by MarieComet** [comment]
Ok, great !
Maybe the first time you saved the option it wasn't saved correctly.
I will add that in the FAQ (double save option) if button do not appears.

**Comment by carfis** [comment]
Yes, that is a good idea ;)

I found an issue with the clone option; I will test a little more tomorrow.

I can't save the template.

![grafik](https://user-images.githubusercontent.com/11331154/35769718-a34e06a6-090f-11e8-9c06-637b6876d5b8.png)
