### ISSUE TITLE
Upgrading to ACF Pro 5.7.0 Creates Javascript Error In Admin

### ISSUE THREAD

**Issue by jroy813** [MarieComet/mc-acf-flexible-template#9]
After upgrading ACF Pro to version 5.7.0, there is a new javascript error in the admin:
"Uncaught TypeError: acf.ajax.extend is not a function". 
This issue is with line 8 of mc-acf-ft-template.js.

This javascript error makes a lot of things in the Wordpress admin broken.

**Comment by MarieComet** [comment]
Hi, looking for that today. Thanks for reporting.

**Comment by MarieComet** [comment]
Please test the last version (https://github.com/MarieComet/mc-acf-flexible-template/commit/493c90df649c8a960a46f2b88bbbb4ed45750a63), tested with ACF 5.7.0.
If you found some bugs, please open new issue(s).
Thanks.

**Comment by jroy813** [comment]
Works like a charm! Thanks for the quick reply, and awesome plugin!!
